### ISSUE TITLE
`Species` should not be required to make a lattice ?

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/AcceleratorLattice.jl#119]
We should have some null species for this case ?

**Comment by DavidSagan** [comment]
I made an issue in AAPC about defining a Null species. Under what circumstances would someone not want to specify a species? Remember that it is not possible to calculate normalized magnet strengths without a reference energy.

**Comment by mattsignorelli** [comment]
Is it not possible to create a toy lattice where _only_ normalized magnet strengths are specified? of course spin tracking is not possible but I am pretty sure this feature exists in MAD

**Comment by DavidSagan** [comment]
Possible but as a practical matter, specifying reference energy and species is a trivial burden.

**Comment by mattsignorelli** [comment]
Are the B-fields stored internally, or the normalized field? I just don't see why the code would impose such a restriction if it isn't necessary

**Comment by DavidSagan** [comment]
Both are stored. It is a convenience thing. The user is allowed to set either.

**Comment by mattsignorelli** [comment]
That seems dangerous, no?

**Comment by DavidSagan** [comment]
The bookkeeping to keep normalized and unnormalized values consistent is fairly trivial so I don't see much danger.

**Comment by DavidSagan** [comment]
In general linac people like setting the field, ring people like setting the normalized field, and simulation people would like to dictate to everyone else what they should do. 😈

**Comment by DavidSagan** [comment]
Closing for now. This issue can be revisited in the future if there is a desire.
