### ISSUE TITLE
change `expand` to general `Lat` constructors

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/AcceleratorLattice.jl#120]

**Comment by mattsignorelli** [comment]
Since `expand` is constructing and returning `Lat`, this should just be a `Lat` constructor

**Comment by mattsignorelli** [comment]
I would also support naming it `Lattice` instead of `Lat`

**Comment by DavidSagan** [comment]
I will change `expand` to `Lat`. In terms of names, there is also `Ele` and not `Element`. This should be discussed to see how people feel.

**Comment by DavidSagan** [comment]
Done.
