### ISSUE TITLE
Bookkeeping changes

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/AcceleratorLattice.jl#128]
Thoughts:

Enable Auto bookkeeping which is triggered when an element parameter is accessed.  
For a lattice, record min/max element that has changed.

**Comment by mattsignorelli** [comment]
The bookkeeper should add to some central data structure during *write* (marking things as "dirty"), and then execute during the next *read*. This should be the default and optionally this could be disabled .

**Comment by DavidSagan** [comment]
Done.
